name: system_time_check
description: a package to help check if system time is set.
version: 1.0.0
repository: https://github.com/yegobox/system_time_check.git
homepage: https://github.com/yegobox/system_time_check.git
publish_to: "none"
environment:
  sdk: ">=2.15.1 <3.0.0"
  flutter: ">=2.5.0"

dependencies:
  flutter:
    sdk: flutter

flutter:
  plugin:
    platforms:
      android:
        package: plugin.flipper.system_time_check
        pluginClass: SystemTimeCheckPlugin
      ios:
        pluginClass: SystemTimeCheckPlugin
